### ISSUE TITLE
Mobile Width is broken by something in the default design

### ISSUE THREAD

**Issue by andrebu** [iamandrebulatov/Theme-Redesign-and-SEO-Overhaul#20]
Despite nothing being more than 100%, even with padding being incorporated and always subtracted from the max width of 100%... the mobile design width is broken by some rogue element in the original design.

**Comment by andrebu** [comment]
Culprit found!   In the theme's styles.css, this horrible negative margin rule at line 235:

``` css
.section-top-title h3 { 
    font-weight: bold; 
    font-size: 13px; 
    text-transform: uppercase;  
    padding: 2px 10px 1px 25px;  
    /* this rule below */
    margin: 0 -25px 0 -25px; 
    /* this rule above */
}
```

The cure is a `margin: 0` for the appropriate mobile query CSS ruleset.
