### ISSUE TITLE
Default YouTube Embeds size is wrong on all device widths

### ISSUE THREAD

**Issue by andrebu** [iamandrebulatov/Theme-Redesign-and-SEO-Overhaul#22]
The static width and height in pixels set by the native embed function messes up the size of all YT Embed videos.

One proposed but untried solution is to use a function in function.php:

``` php
add_filter( 'embed_defaults', 'change_embed_size' );

function change_embed_size() {
    // Adjust values
    return array('width' => 100, 'height' => 100);
}
```

**Comment by iamandrebulatov** [comment]
```css
/* YouTube video Embeds */
.entry .vvqbox.vvqyoutube {
	min-width: 100%;
	display: block;
	width: 100% !important;
	height: auto !important;
}
.entry .vvqbox.vvqyoutube span {
	min-width: 100%;
	display: block;
	width: 100% !important;
	height: auto !important;
}
.entry .vvqyoutube span img {
	height: auto;
}
```

**Comment by iamandrebulatov** [comment]
This fixes #22

**Comment by iamandrebulatov** [comment]
This fixes #22

```css
/* YouTube video Embeds */
.entry .vvqbox.vvqyoutube {
	min-width: 100%;
	display: block;
	width: 100% !important;
	height: auto !important;
}
.entry .vvqbox.vvqyoutube span {
	min-width: 100%;
	display: block;
	width: 100% !important;
	height: auto !important;
}
.entry .vvqyoutube span img {
	height: auto;
}
```

**Comment by iamandrebulatov** [comment]
This fixed #22

```css
/* YouTube video Embeds */
.entry .vvqbox.vvqyoutube {
	min-width: 100%;
	display: block;
	width: 100% !important;
	height: auto !important;
}
.entry .vvqbox.vvqyoutube span {
	min-width: 100%;
	display: block;
	width: 100% !important;
	height: auto !important;
}
.entry .vvqyoutube span img {
	height: auto;
}
```

**Comment by andrebu** [comment]
This fixes #22

``` css
/* YouTube video Embeds */
.entry .vvqbox.vvqyoutube {
    min-width: 100%;
    display: block;
    width: 100% !important;
    height: auto !important;
}
.entry .vvqbox.vvqyoutube span {
    min-width: 100%;
    display: block;
    width: 100% !important;
    height: auto !important;
}
.entry .vvqyoutube span img {
    height: auto;
}
```
